FROM node:13.14-alpine

WORKDIR /client/app

RUN apk add --update --no-cache git bash yarn nano

RUN apk add --update --no-cache autoconf libtool automake alpine-sdk

RUN npm install -g serve

COPY . /client/app/

RUN npm install

RUN npm run build

CMD serve -s build -l 5000
