version: '3.5'
services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik-passerelle"
    networks:
      - semapps
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  fuseki:
    image: stain/jena-fuseki:3.10.0
    container_name: fuseki-passerelle
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: middleware-passerelle
    depends_on:
      - fuseki
    volumes:
      - ./server:/server/app
      - ./../semapps:/semapps
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki-passerelle:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - SEMAPPS_HOME_URL=http://localhost:3000/
      - SEMAPPS_OIDC_ISSUER=https://login.lescommuns.org/auth/realms/master/
      - SEMAPPS_OIDC_CLIENT_ID=passerelle-normandie
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: bash -c "make rollup & make link-yarn && npm run dev"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware.rule=Host(`middleware.localhost`)"
      - "traefik.http.routers.middleware.entrypoints=web"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: frontend-passerelle
    environment:
      - REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - REACT_APP_ADMIN=false
      - PORT=5000
    volumes:
      - ./client:/client/app
      - ./../semapps:/semapps
    networks:
      - semapps
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: bash -c "make rollup & make link-yarn && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`passerelle-normandie.data-players.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  admin:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: admin-passerelle
    volumes:
      - ./client:/client/app
      - ./../semapps:/semapps
    environment:
      - REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - REACT_APP_ADMIN=true
      - PORT=5010
    networks:
      - semapps
    ports:
      - "5010:5010"
    expose:
      - "5010"
    command: bash -c "make rollup & make link-yarn && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.admin.entrypoints=web"

networks:
  semapps:
    name: semapps_network
