version: '3.5'
services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik-passerelle"
    networks:
      - semapps
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=simon.louvet.pro@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  fuseki:
    image: stain/jena-fuseki:3.10.0
    container_name: fuseki-passerelle
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: middleware-passerelle
    depends_on:
      - fuseki
    volumes:
      - ./server/:/app
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki-passerelle:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - SEMAPPS_HOME_URL=https://passerelle-normandie.data-players.com/middleware/
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: bash -c "npm install && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware.rule=Host(`passerelle-normandie.data-players.com`) && PathPrefix(`/middleware/`)"
      - "traefik.http.routers.middleware.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: frontend-passerelle
    environment:
      - REACT_APP_MIDDLEWARE_URL=https://passerelle-normandie.data-players.com/middleware/
      - PORT=5000
    volumes:
      - ./client:/app
    networks:
      - semapps
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: bash -c "npm rebuild && npm install --silent && npm run bootstrap && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`passerelle-normandie.data-players.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

networks:
  semapps:
    name: semapps_network
