version: '3.5'
services:
  fuseki:
    image: semapps/jena-fuseki-webacl:latest
    container_name: fuseki-passerelle
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: middleware-passerelle
    depends_on:
      - fuseki
    volumes:
      - ./server:/app
      - ./../semapps:/semapps
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki-passerelle:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - SEMAPPS_HOME_URL=http://localhost:3000/
      - SEMAPPS_OIDC_ISSUER=https://login.lescommuns.org/auth/realms/master/
      - SEMAPPS_OIDC_CLIENT_ID=passerelle-normandie
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: bash -c "yarn install && yarn run devwithlink"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: frontend-passerelle
    user : node
    environment:
      - REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - REACT_APP_ADMIN=false
      - PORT=5000
    volumes:
      - ./client:/app
      - ./../semapps:/semapps
    networks:
      - semapps
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: bash -c "npm run startwithlink"

  admin:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: admin-passerelle
    user : node
    volumes:
      - ./client:/app
      - ./../semapps:/semapps
    environment:
      - REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - REACT_APP_ADMIN=true
      - PORT=5010
    networks:
      - semapps
    ports:
      - "5010:5010"
    expose:
      - "5010"
    command: bash -c "yarn install && npm run startwithlink"


networks:
  semapps:
    name: semapps_network
